"""Added Status Column in OrderModel

Revision ID: 2a281964f424
Revises: c7fd7b90c3d1
Create Date: 2025-05-10 15:18:13.397831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from enum import Enum

# revision identifiers, used by Alembic.
revision: str = "2a281964f424"
down_revision: Union[str, None] = "c7fd7b90c3d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class OrderStatus(str, Enum):
    PENDING = "pending"
    SHIPPED = "shipped"
    DELIVERED = "delivered"


def upgrade() -> None:
    """Upgrade schema."""

    # Adding ENUM type
    order_status_enum = sa.Enum(OrderStatus, name="orderstatus")
    order_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum("PENDING", "SHIPPED", "DELIVERED", name="orderstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    # ### end Alembic commands ###'

    # Drops the ENUM type from postgreSQL to cleanup.
    sa.Enum(name="orderstatus").drop(op.get_bind())
