"""Add cascade delete relations to user, product, cart, order

Revision ID: c7fd7b90c3d1
Revises:
Create Date: 2025-05-09 12:03:55.394639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7fd7b90c3d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("carts_owner_id_fkey", "carts", type_="foreignkey")
    op.create_foreign_key(
        None, "carts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("orders_owner_id_fkey", "orders", type_="foreignkey")
    op.create_foreign_key(
        None, "orders", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("products_owner_id_fkey", "products", type_="foreignkey")
    op.create_foreign_key(
        None, "products", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        "products_owner_id_fkey", "products", "users", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        "orders_owner_id_fkey", "orders", "users", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.create_foreign_key("carts_owner_id_fkey", "carts", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###
